### ISSUE TITLE
Integration with WikiPathways

### ISSUE THREAD

**Issue by ariutta** [jacobwindsor/Pathway-Presenter-UI#1]
1. Should it be on its own special page similar to [TissueAnalyzer](http://wikipathways.org/index.php/Special:TissueAnalyzer) or should it be part of the main pathway page (e.g., part of the description for [WP554](http://wikipathways.org/index.php/Pathway:WP554))?
2. How should the associated data (markdown) be stored? There's probably too much data to fit into a query parameter. We could add tables to the MySQL database that map between the data and a hash of the data. Then users could visit something like http://www.wikipathways.org/pathway-presenter/WP554?presentation=e75eae5cc72665adec66f315d9a2ee250b91b1cc

Feel free to weigh in if you want to, @AlexanderPico.

**Comment by jacobwindsor** [comment]
I think there's some confusion between the pathway Presenter and the interactive descriptions. This question does not belong here.

While the two ideas are similar (both use manipulation API) they are distinct. Pathway Presenter is really for creating presentations with slides. The interactive descriptions use the markdown syntax and are what's in [MetabMaster](metabmaster.jcbwndsr.com). 

I think this issue should be moved to the general WikiPathways repo.

**Comment by jacobwindsor** [comment]
Please ask for clarification if needed. The ideas are fairly distinct in my head but I can understand where they are mingled.

**Comment by ariutta** [comment]
Sure, please move it as appropriate.

**Comment by jacobwindsor** [comment]
Moved to [here](https://github.com/wikipathways/wikipathways.org/issues/28)
